name: todo_provider
description: A simple Todo app with Provider.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.2
timezone: ^0.9.4
flutter_timezone: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
